version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    IMAGE_REPO_NAME: brain-tasks-app
    IMAGE_TAG: v2
    CLUSTER_NAME: brain-tasks-cluster
    DEPLOYMENT_NAME: brain-tasks-app
    CONTAINER_NAME: brain-tasks-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME

  build:
    commands:
      - echo Build started on `date`
      - docker buildx create --use || true
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64 -t $REPOSITORY_URI:$IMAGE_TAG --push .

  post_build:
    commands:
      - echo Updating Kubernetes deployment image...
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG
      - kubectl rollout status deployment/$DEPLOYMENT_NAME

artifacts:
  files:
    - '**/*'
